openapi: 3.0.0
info:
  title: Quizz App API
  version: 1.0.0
  description: API documentation for the Quizz App, including user authentication and management.

servers:
  - url: http://localhost:3000
    description: Local Development Server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Unique identifier for the user.
        provider:
          type: string
          description: OAuth provider (e.g., google, github).
        providerId:
          type: string
          description: Unique identifier from the OAuth provider.
        displayName:
          type: string
          description: User's display name.
        email:
          type: string
          format: email
          description: User's email address.
        createdAt:
          type: string
          format: date-time
          description: Timestamp when the user was created.

security:
  - bearerAuth: []

paths:
  /auth/google:
    get:
      summary: Initiate Google OAuth Login
      description: Redirects to Google's authentication page to start the OAuth flow.
      tags:
        - Authentication
      responses:
        '302':
          description: Redirect to Google for authentication.

  /auth/google/callback:
    get:
      summary: Google OAuth Callback
      description: Google redirects back to this endpoint after successful authentication. Returns a JWT.
      tags:
        - Authentication
      responses:
        '200':
          description: Successful authentication, returns JWT and user info.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  token:
                    type: string
                    description: JSON Web Token for authentication.
                  user:
                    $ref: '#/components/schemas/User'
        '302':
          description: Redirect to homepage on failure.

  /auth/github:
    get:
      summary: Initiate GitHub OAuth Login
      description: Redirects to GitHub's authentication page to start the OAuth flow.
      tags:
        - Authentication
      responses:
        '302':
          description: Redirect to GitHub for authentication.

  /auth/github/callback:
    get:
      summary: GitHub OAuth Callback
      description: GitHub redirects back to this endpoint after successful authentication. Returns a JWT.
      tags:
        - Authentication
      responses:
        '200':
          description: Successful authentication, returns JWT and user info.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  token:
                    type: string
                    description: JSON Web Token for authentication.
                  user:
                    $ref: '#/components/schemas/User'
        '302':
          description: Redirect to homepage on failure.

  /api/profile:
    get:
      summary: Get Authenticated User Profile
      description: Retrieves the profile of the currently authenticated user.
      tags:
        - User Management
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User profile retrieved successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  user:
                    $ref: '#/components/schemas/User'
        '401':
          description: Unauthorized - No token provided or invalid token.
        '403':
          description: Forbidden - Invalid token.
        '404':
          description: User not found.

  /api/users:
    get:
      summary: Get All Users
      description: Retrieves a list of all registered users.
      tags:
        - User Management
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of users retrieved successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  users:
                    type: array
                    items:
                      $ref: '#/components/schemas/User'
        '401':
          description: Unauthorized - No token provided or invalid token.
        '403':
          description: Forbidden - Invalid token.
        '500':
          description: Internal server error.
